# Generated by Django 6.1.1 on 2026-10-01 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(max_length=200)),
                ("sub", models.CharField(max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC identity",
                "verbose_name_plural": "OIDC identities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "sub"), name="hc_oidc_unique_issuer_sub"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "issuer"), name="hc_oidc_unique_user_issuer"
                    ),
                ],
            },
        ),
    ]
